#!/usr/bin/env node
// Runtime unit tests for siteasy live-mode path containment, design-system
// slug sanitisation, and the contrast parser's colour spaces.
// Pure Node standard library. Run: node tests/unit.mjs
import { resolveInRoot, looksGenerated } from "../skills/siteasy/scripts/live-core.mjs";
import { parseColor, ratioOf } from "../tools/audit/lib/contrast.mjs";
import { runChecks } from "../tools/audit/lib/checks.mjs";
import { dedupeSamples } from "../tools/audit/fetch.mjs";
import { resolve } from "node:path";

let failures = 0;
function ok(name, cond) {
  if (cond) console.log(`  ✅  ${name}`);
  else { console.error(`  ❌  ${name}`); failures++; }
}

console.log("\n── resolveInRoot: stays inside the project root ──");
const root = resolve("/proj");
ok("plain file resolves under root", resolveInRoot(root, "a.txt") === resolve(root, "a.txt"));
ok("nested file resolves under root", resolveInRoot(root, "sub/a.txt") === resolve(root, "sub/a.txt"));
ok("inner ../ that stays inside is allowed", resolveInRoot(root, "sub/../a.txt") === resolve(root, "a.txt"));

console.log("\n── resolveInRoot: rejects escapes ──");
ok("../ escape rejected", resolveInRoot(root, "../escape.txt") === null);
ok("deep ../ escape rejected", resolveInRoot(root, "a/../../escape.txt") === null);
ok("absolute path rejected", resolveInRoot(root, "/etc/passwd") === null);
ok("empty string rejected", resolveInRoot(root, "") === null);
ok("non-string rejected", resolveInRoot(root, null) === null);

console.log("\n── looksGenerated: detects generated-file markers ──");
ok("@generated detected", looksGenerated("// @generated by tool\nbody") === true);
ok("DO NOT EDIT detected", looksGenerated("/* DO NOT EDIT */\nbody") === true);
ok("plain content not flagged", looksGenerated("hello world") === false);

// ---------------------------------------------------------------------------
// contrast.mjs colour parsing.
//
// Anchored on values with known-exact answers (the sRGB primaries round-trip
// through every space, and oklch(62.8% 0.258 29.23) is CSS Color 4's own red
// sample) rather than on whatever this implementation happens to emit.
console.log("\n── parseColor: modern colour spaces ──");
const hex = (c) => {
  const p = parseColor(c);
  return p ? "#" + [p.r, p.g, p.b].map((n) => n.toString(16).padStart(2, "0")).join("") : null;
};

ok("oklch black", hex("oklch(0 0 0)") === "#000000");
ok("oklch white", hex("oklch(1 0 0)") === "#ffffff");
ok("oklch red (CSS Color 4 sample)", hex("oklch(62.8% 0.258 29.23)") === "#ff0000");
ok("oklch percent lightness", hex("oklch(100% 0 0)") === "#ffffff");
ok("oklab achromatic is not sRGB mid-grey", hex("oklab(0.5 0 0)") === "#636363");
ok("lab white", hex("lab(100% 0 0)") === "#ffffff");
ok("lab red (D50)", hex("lab(54.29% 80.8 69.89)") === "#ff0000");
ok("lab green (D50)", hex("lab(87.82% -79.27 80.99)") === "#00ff00");
ok("lab blue (D50)", hex("lab(29.57% 68.3 -112.03)") === "#0000ff");
ok("lch red", hex("lch(54.29% 106.84 40.86)") === "#ff0000");
ok("hsl space syntax", hex("hsl(210 40% 96%)") === "#f1f5f9");
ok("hsl legacy comma syntax", hex("hsl(0, 100%, 50%)") === "#ff0000");
ok("hsl hue wraps", hex("hsl(360 100% 50%)") === "#ff0000");

console.log("\n── parseColor: alpha, legacy syntax, and honest failure ──");
ok("oklch slash alpha", parseColor("oklch(0.7 0.1 200 / 50%)")?.a === 0.5);
ok("hsla slash alpha", parseColor("hsla(120 100% 25% / 0.5)")?.a === 0.5);
ok("hsla legacy 4th arg alpha", parseColor("hsla(120, 100%, 25%, 0.5)")?.a === 0.5);
ok("`none` channel treated as 0", hex("oklch(1 none none)") === "#ffffff");
ok("hex still parses", hex("#f9f8f6") === "#f9f8f6");
ok("rgb still parses", hex("rgb(20 20 24)") === "#141418");
// An unsupported space must stay null so the caller reports "unreadable",
// never a silently wrong ratio.
ok("unsupported color() returns null", parseColor("color(display-p3 1 0 0)") === null);
ok("garbage returns null", parseColor("not-a-colour") === null);

console.log("\n── ratioOf: WCAG anchors ──");
ok("white on black is 21:1", ratioOf("#fff", "#000")?.ratio === 21);
ok("oklch white on oklch black is 21:1", ratioOf("oklch(1 0 0)", "oklch(0 0 0)")?.ratio === 21);
ok("identical colours are 1:1", ratioOf("#808080", "#808080")?.ratio === 1);
// The regression this whole parser exists for: an all-OKLCH token set used to
// return null here, so L-CONTRAST-1 passed without measuring anything.
ok("an OKLCH token pair yields a real ratio", ratioOf("oklch(96% 0.004 265)", "oklch(17% 0.007 265)")?.ratio > 15);
ok("unreadable colour yields null, not a guess", ratioOf("color(display-p3 1 0 0)", "#000") === null);

// ---------------------------------------------------------------------------
// Contrast exemptions.
//
// These test the POLICY, not the plumbing. The exemption exists so an author can
// overrule us out loud; every test below is one way that could rot into a mute
// button, pinned so it cannot. If someone loosens the rule, one of these fails and
// says which promise was dropped.
console.log("\n── contrast exemptions: declared, priced, never silent ──");
const sample = (over) => ({ ratio: 2.0, threshold: 4.5, fontSizePx: 12, exempt: null, exemptReason: null, ...over });
const run = (samples, html = "<html><body><p>x</p></body></html>") =>
  runChecks({ rawHtml: html, computed: { contrastSamples: samples } });
const check = (r, id) => r.find((c) => c.id === id);

const plain = check(run([sample({})]), "contrast-ratio");
ok("an undeclared low sample still fails", plain.verdict === "FAIL" && plain.value.failures === 1);

const declared = check(run([sample({ exempt: "staging", exemptReason: "depicts a defect on purpose" })]), "contrast-ratio");
ok("a properly declared exemption leaves the verdict", declared.verdict === "PASS");
ok("...but is still counted and shown", declared.value.exempt === 1 && declared.value.failures === 0);
ok("...and the report refuses to call it conformant",
  /not WCAG exceptions/.test(declared.detail) && /non-conformant/.test(declared.detail));

// The mute-button paths. Each of these MUST keep the sample in the failure count.
const noReason = check(run([sample({ exempt: "staging" })]), "contrast-ratio");
ok("an exemption without a reason does not excuse anything", noReason.verdict === "FAIL" && noReason.value.failures === 1);
const badCode = check(run([sample({ exempt: "because-i-said-so", exemptReason: "trust me" })]), "contrast-ratio");
ok("an exemption with an invented code does not excuse anything", badCode.verdict === "FAIL" && badCode.value.failures === 1);

// A WCAG-sanctioned code is exempt WITHOUT the non-conformance warning: unlike
// "staging", 1.4.3 actually grants these, so claiming otherwise would be a lie too.
const logo = check(run([sample({ exempt: "logotype", exemptReason: "the mark is the brand" })]), "contrast-ratio");
ok("a real WCAG exception is not smeared with the warning",
  logo.verdict === "PASS" && logo.value.exempt === 1 && !/non-conformant/.test(logo.detail));

console.log("\n── contrast-exempt-undeclared: the exemption pays its own price ──");
const declHtml = (attrs) => `<html><body><b ${attrs}>FAIL</b></body></html>`;
ok("no exemptions on the page passes quietly",
  check(runChecks({ rawHtml: "<html><body><p>x</p></body></html>" }), "contrast-exempt-undeclared").verdict === "PASS");
ok("a bare data-contrast-exempt is itself a defect",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging"') }), "contrast-exempt-undeclared").verdict === "FAIL");
ok("an unknown code is itself a defect",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="whatever" data-contrast-exempt-reason="x"') }), "contrast-exempt-undeclared").verdict === "FAIL");
ok("an empty reason does not count as a reason",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging" data-contrast-exempt-reason="   "') }), "contrast-exempt-undeclared").verdict === "FAIL");
ok("code plus a real reason passes",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging" data-contrast-exempt-reason="depicts the audit overlay"') }), "contrast-exempt-undeclared").verdict === "PASS");
// Static by design: it must work on a page that never booted.
ok("it works render-free, straight off the markup",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging"') }), "contrast-exempt-undeclared").method === "static");

// ---------------------------------------------------------------------------
// dedupeSamples: the sweep must not inflate the count.
//
// Sweeping pages x scroll stops x viewports measures the same element many times.
// If those reach the report raw, one defect becomes ten and the failure count grows
// with how hard you looked — a number that rewards thoroughness with a worse score
// is a units error, and it would push people to sweep less.
console.log("\n── dedupeSamples: one row per element, worst state kept ──");
const smp = (o) => ({ ratio: 5, threshold: 4.5, domPath: "0/1", page: "/", ...o });

ok("the same element across ten states collapses to one",
  dedupeSamples([smp({ ratio: 5 }), smp({ ratio: 6 }), smp({ ratio: 9 })]).length === 1);
ok("...and the survivor is the worst state, not the first or last",
  dedupeSamples([smp({ ratio: 9 }), smp({ ratio: 3.1 }), smp({ ratio: 6 })])[0].ratio === 3.1);
// The nav-theme bug in one line: readable over the first act, failing once the dark
// page slides under it. Averaging or first-seen would both have called this fine.
ok("a pass at scroll 0 does not excuse a failure further down",
  dedupeSamples([smp({ ratio: 5.86, scrollY: 0 }), smp({ ratio: 3.68, scrollY: 2400 })])[0].scrollY === 2400);
ok("the same path on a different page stays a separate finding",
  dedupeSamples([smp({ page: "/" }), smp({ page: "/journey/" })]).length === 2);

// Severity, not raw ratio: responsive type moves the threshold under you, so 3.9:1
// is a pass as large desktop text and a failure as normal mobile text. Comparing raw
// ratios would keep the wrong one and report the page as clean.
const large = smp({ ratio: 3.9, threshold: 3.0 });   // passes: 1.30 severity
const small = smp({ ratio: 4.4, threshold: 4.5 });   // fails:  0.98 severity
ok("worst is measured against the threshold, not by raw ratio",
  dedupeSamples([large, small])[0].ratio === 4.4);

// An element we could not identify must never be merged with another one.
ok("samples without a path are never collapsed together",
  dedupeSamples([smp({ domPath: null }), smp({ domPath: null })]).length === 2);

// ---------------------------------------------------------------------------
// security-headers: which directive holds 'unsafe-inline' is the finding.
//
// Matching the whole CSP string gave one WARN for two unrelated facts: a script hole
// the site must fix, and inline style attributes every animation library needs and no
// site can drop. Advice that cannot be acted on is noise, and noise next to a real
// hole is how the real hole gets ignored.
console.log("\n── security-headers: CSP findings are per directive ──");
const hdrs = (csp) => ({
  "strict-transport-security": "max-age=31536000; includeSubDomains",
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY",
  "referrer-policy": "strict-origin-when-cross-origin",
  "permissions-policy": "camera=()",
  "cross-origin-opener-policy": "same-origin",
  "content-security-policy": csp,
});
const sec = (csp) => runChecks({ rawHtml: "<html><body><p>x</p></body></html>", url: "https://x.test/", headers: hdrs(csp) })
  .find(c => c.id === "security-headers");

const scriptHole = sec("default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self'");
ok("script-src 'unsafe-inline' is a weakness", scriptHole.verdict === "WARN" && scriptHole.value.weak.some(w => /script-src/.test(w)));

// The exact CSP this plugin's own site ships. Motion writes style="" at runtime, so
// style-src-attr must stay open; that must not be reported as the same defect.
const styleOnly = sec("default-src 'self'; script-src 'self' 'sha256-abc='; style-src 'self'; style-src-attr 'unsafe-inline'");
ok("style-src-attr 'unsafe-inline' alone is not a weakness", styleOnly.verdict === "PASS");
ok("...and is not smuggled in as advice either", !styleOnly.value.advisory.some(a => /style-src-attr/.test(a)));

const styleBroad = sec("default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'");
ok("style-src 'unsafe-inline' is advisory, not a weakness", styleBroad.verdict === "PASS" && styleBroad.value.advisory.some(a => /style-src/.test(a)));

// A browser ignores 'unsafe-inline' when hashes are present, so the CSP is not
// actually permissive: calling it weak would be reporting a fact about the string
// rather than about the browser.
const hashed = sec("default-src 'self'; script-src 'self' 'unsafe-inline' 'sha256-abc123='; style-src 'self'");
ok("'unsafe-inline' next to a hash is not a hole (browsers ignore it)",
  hashed.verdict === "PASS" && hashed.value.advisory.some(a => /hashes\/nonces/.test(a)));

// default-src is the fallback: a CSP with no script-src still governs scripts.
const viaDefault = sec("default-src 'self' 'unsafe-inline'; frame-ancestors 'none'");
ok("script-src inherits from default-src when absent", viaDefault.value.weak.some(w => /script-src/.test(w)));
ok("'unsafe-eval' is still caught", sec("script-src 'self' 'unsafe-eval'").value.weak.some(w => /unsafe-eval/.test(w)));

// ---------------------------------------------------------------------------
// The static contrast path: an estimate that knows what it cannot see.
//
// It ran a themed page and reported 4 failures, worst 1.06:1, where the rendered pass
// measured 0. Same fault as the two the rendered path was cleaned of in v1.34.0, still
// alive here because nobody had run this path against a site that re-themes. The eval
// did not drift when it was fixed, which means the 68 fixtures never covered any of
// this: hence these.
console.log("\n── static contrast: skips what a render-free cascade cannot know ──");
const stat = (body, css) => runChecks({ rawHtml: `<html><head><style>${css}</style></head><body>${body}</body></html>` })
  .find(c => c.id === "contrast-ratio");

// Single-token selectors throughout: the CSS model matches tag, .class and #id only
// and skips compound ones on purpose (css.mjs, selectorMatches). Writing `p.ink` here
// tests nothing, because the rule never applies.
//
// A themed page: the light block re-points --paper, the model resolves the light ink
// from :root, and the pair lands light-on-light. Exactly the shape that produced
// 1.06:1 on a wordmark a viewer reads at 16:1.
const themed = stat(
  `<div class="light"><p class="ink">NullToHero</p></div>`,
  `:root{--ink:#ffffff}.light{background:#fbfaf7}.ink{color:var(--ink)}`
);
ok("light ink on light paper is not reported as a failure",
  themed.verdict !== "FAIL");
ok("...and the skip is stated, not silent",
  themed.value?.notJudged?.cascadeArtifacts >= 1 && /light-on-light/.test(themed.detail));

// mix-blend-mode: the cascade's colour is the source of a blend, not the paint. A ratio
// from it is a number no pixel holds, however plausible it looks.
const blend = stat(
  `<div class="wrap"><p class="cap">02 a page exists</p></div>`,
  `.wrap{background:#ffffff}.cap{color:#8a8a86;mix-blend-mode:difference}`
);
ok("blended text is not judged", blend.value?.notJudged?.blended === 1 && !/below AA/.test(blend.detail));

// The exemption is a fact in the markup, so it must hold without a browser. Honouring
// it on one path and not the other made the verdict depend on which flag you ran.
const exemptStatic = stat(
  `<div class="card"><b data-contrast-exempt="staging" data-contrast-exempt-reason="depicts the audit overlay">WARN</b></div>`,
  `.card{background:#dca744}b{color:#ffffff}`
);
ok("a declared exemption is honoured render-free too",
  exemptStatic.verdict !== "FAIL" && exemptStatic.value?.notJudged?.exempt === 1);

// ...but only a well-formed one. The rule has to be identical on both paths.
const bogusStatic = stat(
  `<div class="card"><b data-contrast-exempt="because-i-said-so" data-contrast-exempt-reason="trust me">WARN</b></div>`,
  `.card{background:#dca744}b{color:#ffffff}`
);
ok("an invented code excuses nothing here either", bogusStatic.verdict === "FAIL");

// The guards must not swallow the real thing: mid-grey on white is a genuine defect
// with no cascade excuse, and it still has to fail.
const realFail = stat(`<div class="s"><p>hello there</p></div>`, `.s{background:#ffffff}p{color:#aaaaaa}`);
ok("a real static failure still fails", realFail.verdict === "FAIL" && realFail.value.failures === 1);
ok("...and names the colours so a reader can check it",
  /#aaaaaa/.test(realFail.detail) && realFail.value.worstSamples?.[0]?.fg === "#aaaaaa");

console.log("\n" + "═".repeat(50));
if (failures > 0) {
  console.error(`❌  unit tests FAILED: ${failures} failure(s).`);
  process.exit(1);
}
console.log("✅  unit tests passed.");
process.exit(0);
